### ISSUE TITLE
Arch Labs Forum Signup

### ISSUE THREAD

**Issue by lbhopper** [ArchLabs/archlabs#1]
This is the only place I can access to raise a question regarding the forum signup; **I'm not receiving any verification Emails**.  I've tried multiple times for the past 2 months and nothing (not even in my spam/junk folders). Is the forum no longer maintained?

**Comment by Dobbie03** [comment]
Hi there

Sorry for this issue but I just discovered the issue with the forum email earlier this week.  Not sure if you have read our latest announcement but we are ending ArchLabs so I didn’t see the email issue as something to correct. 

The forum will still be up for a while so if you still want to join please let me know your username and I will manually approve your account. 

Again apologies for the issue.

**Comment by lbhopper** [comment]
If the forum is going to be closed then I will pass on signing up. Sorry I missed the latest announcement. Is there any prep work that I should be aware of when ArchLabs is taken down like PGP signatures and whatnot?

Thank you for the reply

**Comment by Dobbie03** [comment]
You should be okay with most AL packages that require the PGP sigs, but you could just strip out the AL packages as there isn't that much that we really supply other than a few themes, icons and baph the AUR updater.  

There is talk about keeping the forum open as a general Linux forum, or the possibility of moving to Discord or something similar.

**Comment by lbhopper** [comment]
Thanks for the info on the AL packages. in my opinion, Discord would be a good platform to migrate to. it would give a wider range of accessibility to end users for AL.

Thanks again 👍

**Comment by Dobbie03** [comment]
Thanks for the message, I'm leaning towards Discord.  :+1: 

I'll close this issue.
